### PR TITLE
Dependency updates for 1.0.0

### PR DESCRIPTION
**Pull request by AaronPlave**
Updates dependencies to latest.
- Use React 18+
- Update stories and add more documentation

TODO:
- [x] Set up GH action for publishing to NPM
- [x] Fix icon dark mode interaction
- [x] Fix icon filename case sensitivity

### CODE REVIEW

**Review by duranb — COMMENTED** [review]
Amazing! I've been able to export some svg files as React components on another project, would that make it easier to sync the icons from stellar or is that not possible here?

**Review by duranb — CHANGES_REQUESTED** [review]
Do you mind adding an `.nvmrc` file? `nvm use` uses the version defined in there.

**Review by duranb — APPROVED** [review]
I think this is working great! The only issue is that if you're on dark mode and view the icons story, the icons get set to a lighter color and are no longer clearly visible because the background stays white. It at least showcases that the icons inherit the colors correctly lol. Not sure if it's something to block this PR, otherwise I think this is good to go!

**Comment by AaronPlave** [comment]
Mostly fixed the icon issue. Dark theming in general is definitely another task that hasn't really been tackled yet in this library.

**Pull request merged**
